<?php

namespace App\Filament\Resources\Responsables;

use App\Filament\Resources\Responsables\Pages\ManageResponsables;
use App\Models\Responsable;
use App\Traits\AlmacenSchemas;
use BackedEnum;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ForceDeleteAction;
use Filament\Actions\ForceDeleteBulkAction;
use Filament\Actions\RestoreAction;
use Filament\Actions\RestoreBulkAction;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Width;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Str;
use UnitEnum;

class ResponsableResource extends Resource
{
    use AlmacenSchemas;

    protected static ?string $model = Responsable::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedUserGroup;

    protected static string|UnitEnum|null $navigationGroup = 'Gestión de Almacén';

    protected static ?int $navigationSort = 85;

    protected static ?string $recordTitleAttribute = 'cedula';

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components(self::formResponsable())
            ->columns(1);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('cedula')
            ->columns([
                TextColumn::make('responsable')
                    ->default(fn (Responsable $record): string => Str::upper($record->nombre))
                    ->description(fn (Responsable $record): string => formatoMillares($record->cedula, 0), position: 'above')
                    ->hiddenFrom('md'),
                TextColumn::make('nombre')
                    ->searchable()
                    ->visibleFrom('md'),
                TextColumn::make('cedula')
                    ->numeric()
                    ->searchable()
                    ->visibleFrom('md')
                    ->alignCenter(),
                TextColumn::make('telefono')
                    ->searchable()
                    ->visibleFrom('md'),
                TextColumn::make('empresa')
                    ->searchable()
                    ->wrap()
                    ->visibleFrom('md'),
            ])
            ->filters([
                TrashedFilter::make(),
            ])
            ->recordActions([
                ActionGroup::make([
                    EditAction::make()
                        ->modalWidth(Width::Small),
                    DeleteAction::make(),
                    ForceDeleteAction::make(),
                    RestoreAction::make(),
                ]),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make()
                        ->authorizeIndividualRecords('delete'),
                    ForceDeleteBulkAction::make()
                        ->authorizeIndividualRecords('forceDelete'),
                    RestoreBulkAction::make()
                        ->authorizeIndividualRecords('restore'),
                ]),
                Action::make('actualizar')
                    ->icon(Heroicon::ArrowPath)
                    ->iconButton(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ManageResponsables::route('/'),
        ];
    }

    public static function getRecordRouteBindingEloquentQuery(): Builder
    {
        return parent::getRecordRouteBindingEloquentQuery()
            ->withoutGlobalScopes([
                SoftDeletingScope::class,
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->orderByDesc('created_at'); // TODO: Change the autogenerated stub
    }
}
